# Welcome to Jekyll!
#

# Site settings
title: Fighting Squid Robot Page
description: |
  Fierce contender in the [2016 Engineering Physics Robot Competition](http://projectlab.engphys.ubc.ca/enph-253-2016/), 
  a miniaturized UBER + Automated Driving challenge as featured [here](http://www.metronews.ca/news/vancouver/2016/08/05/ubc-engineering-robot-competition-features-driverless-cars.html)
  and [here](http://globalnews.ca/video/2866243/ubc-students-test-out-automated-robot-cars/).
owner: The sea # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fighting-squid.github.io" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
